version: 2.1

orbs:
  node: circleci/node@5.0.3

defaults: &defaults
  resource_class: small
  docker:
    - image: 'cimg/node:18.17.1'

jobs:
  install:
    <<: *defaults
    steps:
      - checkout
      - node/install-packages
      - persist_to_workspace:
          root: .
          paths:
            - 'node_modules'

  check:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Typecheck
          command: npm run typecheck
      - run:
          name: ESLint
          command: npm run lint

  test_jest:
    <<: *defaults
    resource_class: medium
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Test Jest
          command: npm run test:ci
      - store_artifacts:
          path: ./coverage
      - store_test_results:
          path: ./
      - persist_to_workspace:
          root: .
          paths:
            - 'coverage'
            - 'junit.xml'

workflows:
  main:
    jobs:
      - install
      - check:
          requires:
            - install
      - test_jest:
          requires:
            - install
